using PdfSharp.Drawing;
using PdfSharp.Pdf;

namespace Stampd.Engine.Smoke;

/// <summary>
/// Generates a synthetic source PDF and a synthetic signature image so the smoke test is
/// fully self-contained (no asset files checked into the repo).
/// </summary>
internal static class SampleAssetFactory
{
    /// <summary>
    /// Builds a one-page Letter-sized PDF with placeholder contract text and a labelled
    /// signature box outline at the percentage coordinates the smoke test will stamp into.
    /// </summary>
    public static byte[] BuildSourcePdf()
    {
        using var document = new PdfDocument();
        document.Info.Title = "Stampd Engine Spike — Sample Contract";
        document.Info.Author = "Stampd";

        var page = document.AddPage();
        page.Size = PdfSharp.PageSize.Letter;

        using var gfx = XGraphics.FromPdfPage(page);

        var titleFont = new XFont("Helvetica", 18, XFontStyleEx.Bold);
        var bodyFont = new XFont("Helvetica", 11, XFontStyleEx.Regular);
        var labelFont = new XFont("Helvetica", 9, XFontStyleEx.Italic);

        var pageW = page.Width.Point;
        var pageH = page.Height.Point;

        gfx.DrawString(
            "Stampd Engine — Spike Contract",
            titleFont,
            XBrushes.Black,
            new XRect(0, 50, pageW, 30),
            XStringFormats.TopCenter);

        var body = string.Join(
            "  ",
            "This is a synthetic document generated by the Stampd engine smoke test.",
            "Its only purpose is to give the engine something to stamp and something to sign.",
            "If you can open this PDF and see a green check in Adobe Acrobat, the signing pipeline works.");

        gfx.DrawString(
            body,
            bodyFont,
            XBrushes.Black,
            new XRect(72, 120, pageW - 144, 200),
            XStringFormats.TopLeft);

        // Outline the signature box so it's easy to see where the stamp will land.
        // Matches the SignatureField bounds in Program.cs (10% from left, 80% from top, 30% wide, 8% tall).
        var sigBox = new XRect(
            0.10 * pageW,
            0.80 * pageH,
            0.30 * pageW,
            0.08 * pageH);

        var dashed = new XPen(XColors.Gray, 0.5)
        {
            DashStyle = XDashStyle.Dash,
        };
        gfx.DrawRectangle(dashed, sigBox);

        gfx.DrawString(
            "Signature",
            labelFont,
            XBrushes.Gray,
            new XRect(sigBox.X, sigBox.Y - 14, sigBox.Width, 12),
            XStringFormats.TopLeft);

        using var ms = new MemoryStream();
        document.Save(ms);
        return ms.ToArray();
    }

    /// <summary>
    /// Builds a tiny PNG that looks like a signature: a stylised cursive scrawl on a
    /// transparent background. Renders via PDFsharp + a temporary PDF page so we don't
    /// need to take a SkiaSharp dependency just for the smoke test.
    /// </summary>
    /// <remarks>
    /// PDFsharp can't write PNG directly, so we rasterise a tiny PDF page to an in-memory
    /// PNG using SkiaSharp. Falls back to a plain PNG with text if SkiaSharp isn't present.
    /// For the spike, a colored PNG produced inline is sufficient.
    /// </remarks>
    public static byte[] BuildSignaturePng()
    {
        // Minimal 200x80 RGBA PNG with a hand-drawn-looking signature stroke.
        // Uses SkiaSharp because we already reference it from Stampd.Engine.csproj.
        using var bitmap = new SkiaSharp.SKBitmap(400, 160);
        using (var canvas = new SkiaSharp.SKCanvas(bitmap))
        {
            canvas.Clear(SkiaSharp.SKColors.Transparent);

            using var stroke = new SkiaSharp.SKPaint
            {
                Color = new SkiaSharp.SKColor(20, 30, 90),
                IsAntialias = true,
                Style = SkiaSharp.SKPaintStyle.Stroke,
                StrokeWidth = 3.5f,
                StrokeCap = SkiaSharp.SKStrokeCap.Round,
                StrokeJoin = SkiaSharp.SKStrokeJoin.Round,
            };

            using var path = new SkiaSharp.SKPath();
            path.MoveTo(20, 110);
            path.CubicTo(60, 30, 90, 150, 130, 80);
            path.CubicTo(160, 30, 200, 130, 240, 70);
            path.CubicTo(280, 30, 320, 140, 380, 80);
            canvas.DrawPath(path, stroke);

            // Underline flourish.
            using var underline = new SkiaSharp.SKPaint
            {
                Color = new SkiaSharp.SKColor(20, 30, 90),
                IsAntialias = true,
                Style = SkiaSharp.SKPaintStyle.Stroke,
                StrokeWidth = 1.5f,
                StrokeCap = SkiaSharp.SKStrokeCap.Round,
            };
            canvas.DrawLine(20, 135, 380, 135, underline);
        }

        using var image = SkiaSharp.SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SkiaSharp.SKEncodedImageFormat.Png, 100);
        return data.ToArray();
    }
}
