// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stampd.Infrastructure;

#nullable disable

namespace Stampd.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(StampdDbContext))]
    [Migration("20260606130000_V12EpochSortColumns")]
    partial class V12EpochSortColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        #pragma warning disable 612, 618
                    modelBuilder
                        .HasAnnotation("ProductVersion", "10.0.8")
                        .HasAnnotation("Relational:MaxIdentifierLength", 63);
        
                    NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        
                    modelBuilder.Entity("Stampd.Core.Entities.AuditEvent", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<string>("DocumentHashAtEvent")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<int>("EventType")
                                .HasColumnType("integer");
        
                            b.Property<string>("GeoCity")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");
        
                            b.Property<string>("GeoCountry")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<string>("IpAddress")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<bool>("IsRedacted")
                                .HasColumnType("boolean");
        
                            b.Property<DateTimeOffset>("OccurredAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("PayloadJson")
                                .HasColumnType("text");
        
                            b.Property<Guid?>("RecipientId")
                                .HasColumnType("uuid");
        
                            b.Property<Guid>("SigningRequestId")
                                .HasColumnType("uuid");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.HasKey("Id");
        
                            b.HasIndex("RecipientId");
        
                            b.HasIndex("SigningRequestId", "OccurredAtUtc");
        
                            b.HasIndex("TenantId", "EventType");
        
                            b.HasIndex("TenantId", "OccurredAtUtc");
        
                            b.ToTable("AuditEvents", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.BulkSendJob", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<DateTimeOffset?>("CompletedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<int>("CompletedRows")
                                .HasColumnType("integer");
        
                            b.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<long>("CreatedAtUtcEpochMs")
                                .HasColumnType("bigint");
        
                            b.Property<Guid>("DocumentTemplateId")
                                .HasColumnType("uuid");
        
                            b.Property<int>("FailedRows")
                                .HasColumnType("integer");
        
                            b.Property<string>("FailedRowsJson")
                                .IsRequired()
                                .HasColumnType("text");
        
                            b.Property<string>("Message")
                                .HasMaxLength(4096)
                                .HasColumnType("character varying(4096)");
        
                            b.Property<string>("PendingRowsJson")
                                .IsRequired()
                                .HasColumnType("text");
        
                            b.Property<DateTimeOffset?>("StartedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<int>("Status")
                                .HasColumnType("integer");
        
                            b.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<int>("TotalRows")
                                .HasColumnType("integer");
        
                            b.HasKey("Id");
        
                            b.HasIndex("Status", "CreatedAtUtcEpochMs");
        
                            b.HasIndex("TenantId", "Status");
        
                            b.ToTable("BulkSendJobs", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.DocumentTemplate", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<Guid>("ConcurrencyToken")
                                .IsConcurrencyToken()
                                .HasColumnType("uuid");
        
                            b.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<long>("CreatedAtUtcEpochMs")
                                .HasColumnType("bigint");
        
                            b.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");
        
                            b.Property<string>("Description")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");
        
                            b.Property<bool>("IsArchived")
                                .HasColumnType("boolean");
        
                            b.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");
        
                            b.Property<string>("SourcePdfSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<string>("SourcePdfStorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<DateTimeOffset>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.HasKey("Id");
        
                            b.HasIndex("TenantId", "CreatedAtUtcEpochMs");
        
                            b.HasIndex("TenantId", "IsArchived");
        
                            b.HasIndex("TenantId", "Name");
        
                            b.ToTable("DocumentTemplates", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.Recipient", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<string>("AccessToken")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");
        
                            b.Property<string>("DeclineReason")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");
        
                            b.Property<DateTimeOffset?>("DeclinedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)");
        
                            b.Property<DateTimeOffset?>("FirstViewedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("IdentityVerificationMethod")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<DateTimeOffset?>("IdentityVerifiedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<DateTimeOffset?>("InvitedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");
        
                            b.Property<Guid?>("RoleId")
                                .HasColumnType("uuid");
        
                            b.Property<int>("RoutingOrder")
                                .HasColumnType("integer");
        
                            b.Property<DateTimeOffset?>("SignedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<Guid>("SigningRequestId")
                                .HasColumnType("uuid");
        
                            b.Property<int>("Status")
                                .HasColumnType("integer");
        
                            b.Property<string>("SubmittedFieldValuesJson")
                                .HasColumnType("text");
        
                            b.HasKey("Id");
        
                            b.HasIndex("AccessToken")
                                .IsUnique();
        
                            b.HasIndex("RoleId");
        
                            b.HasIndex("SigningRequestId", "RoutingOrder");
        
                            b.ToTable("Recipients", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.SignedDocumentRecord", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<string>("ContentSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<int>("PAdESLevel")
                                .HasColumnType("integer");
        
                            b.Property<string>("SealingKeyIdentifier")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.Property<string>("SealingProviderName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<DateTimeOffset>("SignedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<Guid>("SigningRequestId")
                                .HasColumnType("uuid");
        
                            b.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<string>("TimestampAuthorityUrl")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.HasKey("Id");
        
                            b.HasIndex("ContentSha256");
        
                            b.HasIndex("SigningRequestId")
                                .IsUnique();
        
                            b.HasIndex("TenantId", "SignedAtUtc");
        
                            b.ToTable("SignedDocumentRecords", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.SigningRequest", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<DateTimeOffset?>("CompletedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<Guid>("ConcurrencyToken")
                                .IsConcurrencyToken()
                                .HasColumnType("uuid");
        
                            b.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");
        
                            b.Property<DateTimeOffset?>("DeclinedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<Guid>("DocumentTemplateId")
                                .HasColumnType("uuid");
        
                            b.Property<DateTimeOffset?>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("Message")
                                .HasMaxLength(4096)
                                .HasColumnType("character varying(4096)");
        
                            b.Property<DateTimeOffset?>("SentAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<int>("Status")
                                .HasColumnType("integer");
        
                            b.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<string>("TerminationReason")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");
        
                            b.Property<DateTimeOffset?>("VoidedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.HasKey("Id");
        
                            b.HasIndex("DocumentTemplateId");
        
                            b.HasIndex("TenantId", "CreatedAtUtc");
        
                            b.HasIndex("TenantId", "Status");
        
                            b.ToTable("SigningRequests", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.TemplateField", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<Guid?>("AssignedRoleId")
                                .HasColumnType("uuid");
        
                            b.Property<double>("BoundsHeight")
                                .HasColumnType("double precision");
        
                            b.Property<double>("BoundsWidth")
                                .HasColumnType("double precision");
        
                            b.Property<double>("BoundsX")
                                .HasColumnType("double precision");
        
                            b.Property<double>("BoundsY")
                                .HasColumnType("double precision");
        
                            b.Property<string>("DefaultValue")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");
        
                            b.Property<Guid>("DocumentTemplateId")
                                .HasColumnType("uuid");
        
                            b.Property<bool>("IsRequired")
                                .HasColumnType("boolean");
        
                            b.Property<int>("Kind")
                                .HasColumnType("integer");
        
                            b.Property<string>("Label")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");
        
                            b.Property<int>("PageNumber")
                                .HasColumnType("integer");
        
                            b.HasKey("Id");
        
                            b.HasIndex("AssignedRoleId");
        
                            b.HasIndex("DocumentTemplateId", "PageNumber");
        
                            b.ToTable("TemplateFields", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.TemplateRecipientRole", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<Guid>("DocumentTemplateId")
                                .HasColumnType("uuid");
        
                            b.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");
        
                            b.Property<bool>("RequiresIdentityVerification")
                                .HasColumnType("boolean");
        
                            b.Property<int>("RoutingOrder")
                                .HasColumnType("integer");
        
                            b.HasKey("Id");
        
                            b.HasIndex("DocumentTemplateId", "RoutingOrder");
        
                            b.ToTable("TemplateRecipientRoles", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.WebhookDelivery", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<int>("AttemptCount")
                                .HasColumnType("integer");
        
                            b.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<int>("EventType")
                                .HasColumnType("integer");
        
                            b.Property<string>("LastErrorMessage")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");
        
                            b.Property<int?>("LastResponseStatus")
                                .HasColumnType("integer");
        
                            b.Property<DateTimeOffset>("NextAttemptAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<long>("NextAttemptAtUtcEpochMs")
                                .HasColumnType("bigint");
        
                            b.Property<string>("PayloadJson")
                                .IsRequired()
                                .HasColumnType("text");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<Guid>("WebhookEndpointId")
                                .HasColumnType("uuid");
        
                            b.HasKey("Id");
        
                            b.HasIndex("NextAttemptAtUtc");
        
                            b.HasIndex("NextAttemptAtUtcEpochMs");
        
                            b.HasIndex("WebhookEndpointId");
        
                            b.ToTable("WebhookDeliveries", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.WebhookEndpoint", b =>
                        {
                            b.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");
        
                            b.Property<int>("ConsecutiveFailures")
                                .HasColumnType("integer");
        
                            b.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<bool>("IsActive")
                                .HasColumnType("boolean");
        
                            b.Property<DateTimeOffset?>("LastDeliveryAttemptAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<string>("Secret")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");
        
                            b.Property<string>("SubscribedEvents")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");
        
                            b.Property<Guid>("TenantId")
                                .HasColumnType("uuid");
        
                            b.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)");
        
                            b.HasKey("Id");
        
                            b.HasIndex("TenantId", "IsActive");
        
                            b.ToTable("WebhookEndpoints", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Infrastructure.Identity.OtpChallengeEntity", b =>
                        {
                            b.Property<string>("VerificationId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.Property<string>("CodeHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");
        
                            b.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<DateTimeOffset>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone");
        
                            b.Property<int>("FailedAttempts")
                                .HasColumnType("integer");
        
                            b.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)");
        
                            b.Property<string>("Salt")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");
        
                            b.HasKey("VerificationId");
        
                            b.HasIndex("ExpiresAtUtc");
        
                            b.ToTable("OtpChallenges", (string)null);
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.AuditEvent", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.Recipient", "Recipient")
                                .WithMany()
                                .HasForeignKey("RecipientId")
                                .OnDelete(DeleteBehavior.SetNull);
        
                            b.HasOne("Stampd.Core.Entities.SigningRequest", "SigningRequest")
                                .WithMany("AuditEvents")
                                .HasForeignKey("SigningRequestId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
        
                            b.Navigation("Recipient");
        
                            b.Navigation("SigningRequest");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.Recipient", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.TemplateRecipientRole", "Role")
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.SetNull);
        
                            b.HasOne("Stampd.Core.Entities.SigningRequest", "SigningRequest")
                                .WithMany("Recipients")
                                .HasForeignKey("SigningRequestId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
        
                            b.Navigation("Role");
        
                            b.Navigation("SigningRequest");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.SignedDocumentRecord", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.SigningRequest", "SigningRequest")
                                .WithOne("SignedDocument")
                                .HasForeignKey("Stampd.Core.Entities.SignedDocumentRecord", "SigningRequestId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
        
                            b.Navigation("SigningRequest");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.SigningRequest", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.DocumentTemplate", "DocumentTemplate")
                                .WithMany()
                                .HasForeignKey("DocumentTemplateId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
        
                            b.Navigation("DocumentTemplate");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.TemplateField", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.TemplateRecipientRole", "AssignedRole")
                                .WithMany("Fields")
                                .HasForeignKey("AssignedRoleId")
                                .OnDelete(DeleteBehavior.SetNull);
        
                            b.HasOne("Stampd.Core.Entities.DocumentTemplate", "DocumentTemplate")
                                .WithMany("Fields")
                                .HasForeignKey("DocumentTemplateId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
        
                            b.Navigation("AssignedRole");
        
                            b.Navigation("DocumentTemplate");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.TemplateRecipientRole", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.DocumentTemplate", "DocumentTemplate")
                                .WithMany("Roles")
                                .HasForeignKey("DocumentTemplateId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
        
                            b.Navigation("DocumentTemplate");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.WebhookDelivery", b =>
                        {
                            b.HasOne("Stampd.Core.Entities.WebhookEndpoint", "WebhookEndpoint")
                                .WithMany()
                                .HasForeignKey("WebhookEndpointId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
        
                            b.Navigation("WebhookEndpoint");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.DocumentTemplate", b =>
                        {
                            b.Navigation("Fields");
        
                            b.Navigation("Roles");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.SigningRequest", b =>
                        {
                            b.Navigation("AuditEvents");
        
                            b.Navigation("Recipients");
        
                            b.Navigation("SignedDocument");
                        });
        
                    modelBuilder.Entity("Stampd.Core.Entities.TemplateRecipientRole", b =>
                        {
                            b.Navigation("Fields");
                        });
        #pragma warning restore 612, 618
                }
    }
}
